import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        '404': '404.html',
        'auditlog-staalbouw': 'auditlog-staalbouw.html',
        'cancel': 'cancel.html',
        'ce-dossier': 'ce-dossier.html',
        'ce-markering-staal': 'ce-markering-staal.html',
        'ce-markering': 'ce-markering.html',
        'checkout': 'checkout.html',
        'contact': 'contact.html',
        'demo': 'demo.html',
        'documentatie': 'documentatie.html',
        'faq': 'faq.html',
        'features-index': 'features/index.html',
        'index': 'index.html',
        'iso-3834': 'iso-3834.html',
        'iso-5817': 'iso-5817.html',
        'lascontrole': 'lascontrole.html',
        'lasdocumentatie': 'lasdocumentatie.html',
        'legal-privacy': 'legal/privacy.html',
        'legal-security': 'legal/security.html',
        'legal-terms': 'legal/terms.html',
        'nen-en-1090': 'nen-en-1090.html',
        'onboarding': 'onboarding.html',
        'over-ons': 'over-ons.html',
        'planning': 'planning.html',
        'pricing': 'pricing.html',
        'privacy': 'privacy.html',
        'security': 'security.html',
        'set-password': 'set-password.html',
        'software': 'software.html',
        'success': 'success.html',
        'app-auditlog': 'app/auditlog.html',
        'app-change-password': 'app/change-password.html',
        'app-dashboard': 'app/dashboard.html',
        'app-forgot-password': 'app/forgot-password.html',
        'app-login': 'app/login.html',
        'app-logout': 'app/logout.html',
        'app-projects': 'app/projects.html',
        'app-requirements': 'app/requirements.html',
        'app-reset-password': 'app/reset-password.html',
        'app-settings': 'app/settings.html',
        'app-set-password': 'app/set-password.html',
        'app-subscription': 'app/subscription.html',
      }
    }
  },
  server: { host: '127.0.0.1', port: 5173 }
});
